controllers:
    resource: ../src/Controller/
    type: attribute


products_edit:
    path: '/products/edit/{id}'
    controller: 'App\Controller\ProductsController::edit'



products_delete:
    path: '/products/suppression/{id}'
    controller: 'App\Controller\ProductsController::delete'



arrivages_edit:
    path: '/arrivages/edit/{id}'
    controller: 'App\Controller\ArrivagesController::edit'



arrivage_delete:
    path: '/arrivages/suppression/{id}'
    controller: 'App\Controller\ArrivagesController::delete'


user_edit:
    path: '/utilisateur/edition/{id}'
    controller: 'App\Controller\UserController::edit'


# config/routes.yaml
user.edit.password:
    path: '/utilisateur/edition-mot-de-passe/{id}'
    controller: 'App\Controller\UserController::editPassword'
