controllers:
    resource: ../src/Controller/
    type: attribute


products_edit:
    path: '/products/{id}/edit'
    controller: 'App\Controller\ProductsController::edit'



products_delete:
    path: '/products/{id}/delete/'
    controller: 'App\Controller\ProductsController::delete'
